### ISSUE TITLE
fatal error: 'cstdint' file not found

### ISSUE THREAD

**Issue by yangwao** [ranisalt/node-argon2#15]
Looks like problem with Clang/GCC? 
```
wao@astrid~/P/s/lab> g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

wao@astrid~/P/s/lab> npm install argon2

> argon2@0.7.0 install /Users/wao/node_modules/argon2
> node-gyp rebuild

  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  LIBTOOL-STATIC Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
../src/argon2_node.cpp:4:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wao/node_modules/argon2
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/wao/package.json'
npm WARN EPACKAGEJSON wao No description
npm WARN EPACKAGEJSON wao No repository field.
npm WARN EPACKAGEJSON wao No README data
npm WARN EPACKAGEJSON wao No license field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "argon2"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! argon2@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.7.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the argon2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls argon2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wao/Projects/saferpass/lab/npm-debug.log
```

**Comment by ranisalt** [comment]
Most certainly. The cstdint header maps fixed-width types like `uint32_t` to arch-specific types like `int` and is a must since architecture specific integers might interfere.

**Comment by cgmb** [comment]
I can reproduce. Here's the command I get when using `node-gyp configure rebuild --verbose`:

>   c++ '-DNODE_GYP_MODULE_NAME=argon2' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/cgmb/.node-gyp/5.5.0/include/node -I/Users/cgmb/.node-gyp/5.5.0/src -I/Users/cgmb/.node-gyp/5.5.0/deps/uv/include -I/Users/cgmb/.node-gyp/5.5.0/deps/v8/include -I../node_modules/nan -I../argon2/include  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/argon2/src/argon2_node.o.d.raw   -c -o Release/obj.target/argon2/src/argon2_node.o ../src/argon2_node.cpp

OSX is a bit of a mystery to me, but the problem comes from `-mmacosx-version-min=10.5`. OSX 10.5 released in 2007, before `cstdint` existed. I presume we're stuck using the 10.5 standard library unless we specify otherwise. I'm not entirely sure of the implications of changing that.

Using the C99 header `stdint.h` seems like the easiest fix. Support for that was added long ago for clang and gcc. Microsoft added it in MSVC 2010.

Of course, C++11 support will be limited so long as it only includes what was available in 10.5.

**Comment by ranisalt** [comment]
Searching led me to know that OS X does not have `cstdint` but only `stdint.h` (even today as of OS X 10.9), and I prefer the former since it does not throw a bunch of typedefs into the global namespace.

Could someone test if changing [this line](https://github.com/ranisalt/node-argon2/blob/master/src/argon2_node.cpp#L4) to that:
```cpp
#ifdef __APPLE__
namespace std {
#include <stdint.h>
}
#else
#include <cstdint>
#endif
```
Fixes it? Seems good enough to try, and I don't have OS X available to test.

**Comment by cgmb** [comment]
Adding definitions to the std namespace is not technically allowed, and including a system file within any namespace seems like a bad idea to me.

We can always rely on `stdint.h` being there. It's included as the first line of `argon2.h`, and is used as part of the argon2 public interface. We actually don't *really* need to include it ourselves.

**Comment by ranisalt** [comment]
Should be fixed on e3f2aa4 and I'll try to add osx to the Travis build matrix, but I can't promise since Node+OSX is not supported yet.

**Comment by divmgl** [comment]
I forked this just now to fix this issue, not sure if you agree with the changes. Thanks.

https://github.com/divmgl/node-argon2

**Comment by cgmb** [comment]
You had it right in c4b3e4cc7c99e64a09b0b1d6c1a12ce1084ddb70. The using declaration needs to go too.

**Comment by ranisalt** [comment]
> You had it right in c4b3e4c. The using declaration needs to be removed too.

Ok, cleaned that and other unused stuff on e8e028a

**Comment by yangwao** [comment]
Looks like it fixed some other thing, but still doesn't work for me.

```
wao@astrid~/P/node-argon2> git log -1|grep commit
commit e8e028a2e8bee68fab6d48c7ff75265217fd53bb

wao@astrid~/P/node-argon2> node-gyp configure rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'configure',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.2.1
gyp info using node@5.5.0 | darwin | x64
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (/usr/local/lib/node_modules/node-gyp/node_modules/which/which.js:63:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/node-gyp/node_modules/which/which.js:72:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/node-gyp/node_modules/which/which.js:81:16
gyp verb `which` failed     at /usr/local/lib/node_modules/node-gyp/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /usr/local/lib/node_modules/node-gyp/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.5.0
gyp verb command install [ '5.5.0' ]
gyp verb install input version string "5.5.0"
gyp verb install installing version: 5.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.5.0
gyp verb build dir attempting to create "build" dir: /Users/wao/Projects/node-argon2/build
gyp verb build dir "build" dir needed to be created? null
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/wao/Projects/node-argon2/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/wao/Projects/node-argon2/config.gypi
gyp verb common.gypi checking for gypi file: /Users/wao/Projects/node-argon2/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wao/Projects/node-argon2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wao/.node-gyp/5.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/wao/.node-gyp/5.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/wao/Projects/node-argon2',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python" in the PATH
gyp verb `which` succeeded /usr/bin/python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.5.0
gyp verb command install [ '5.5.0' ]
gyp verb install input version string "5.5.0"
gyp verb install installing version: 5.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.5.0
gyp verb build dir attempting to create "build" dir: /Users/wao/Projects/node-argon2/build
gyp verb build dir "build" dir needed to be created? /Users/wao/Projects/node-argon2/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/wao/Projects/node-argon2/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/wao/Projects/node-argon2/config.gypi
gyp verb common.gypi checking for gypi file: /Users/wao/Projects/node-argon2/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wao/Projects/node-argon2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wao/.node-gyp/5.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/wao/.node-gyp/5.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/wao/Projects/node-argon2',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/wao/.node-gyp/5.5.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/libargon2/argon2/src/argon2.o', needed by `Release/argon2.a'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "rebuild" "--verbose"
gyp ERR! cwd /Users/wao/Projects/node-argon2
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by ranisalt** [comment]
Please open another issue then. But it seems to me to be completely a node-gyp or Mac OS X problem, so if possible also open an issue on node-gyp's repo.

**Comment by cgmb** [comment]
To build from this repository, you need to run `git submodule init --update` after cloning.

**Comment by cgmb** [comment]
Err... Or was that `git submodule update --init`? I think the second one.

**Comment by yangwao** [comment]
@cgmb it did the work! :) 
@ranisalt could you please push to npm new version? works ok from e8e028a2e8bee68fab6d48c7ff75265217fd53bb
Thanks!

**Comment by ranisalt** [comment]
Sure! v0.8.0 is out :)
